name: build-x86_64

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3.5.0
      - name: CMake build
        run: mkdir ${{ github.workspace }}/build && cd ${{ github.workspace }}/build && cmake .. && cmake --build . --config Release
      - uses: actions/upload-artifact@v3
        with:
          name: devops-binary
          path: ${{ github.workspace }}/build/devopsExample
        
